### ISSUE TITLE
Ask for confirmation for the new release name

### ISSUE THREAD

**Issue by MichaelMure** [webpro/release-it#114]
Hello,

The `buildCommand` I have for my project take a lot of time (building and packaging for multiple platform). Half the time I mix up between `minor` and `patch` and end up with the wrong version number and I have to clean things and start over.

It would be nice imho to get asked to validate the new version name in the beginning of the process, before any files are touched. It would also help when creating the .release.json the first time and messing with the `tagName` config.

I just noticed that the new version number (not the full version name) is displayed at the beginning, but it disappear quickly with the buildCommand running.

**Comment by webpro** [comment]
Yeah, I agree it may be a good idea to add a confirmation step for the bumped version. Also for people new to this tool.

Another feature that might be useful: a `cleanupCommand` to automate the clean up in case anything went wrong. What do you think?

> I just noticed that the new version number (not the full version name) is displayed at the beginning, but it disappear quickly with the buildCommand running.

Do you mean it disappears, because the output is mangled by release-it, or does your `buildCommand` have a lot of output?

While looking into this, I saw a regression in v3: the `${version}` variable wasn't available in (template) commands anymore, while their output was not logged. I've just released a patch with [v3.0.1](https://github.com/webpro/release-it/releases/tag/3.0.1).

Now, you can do something like this in your `buildCommand`:

```
"buildCommand": "echo ${version} && build"
```

And, not sure how helpful, this is also possible (in the end it's just shell):

```
"buildCommand": "printf '${src.tagName}' '${version}' && sleep 3 && build"
```

**Comment by MichaelMure** [comment]
> Do you mean it disappears, because the output is mangled by release-it, or does your buildCommand have a lot of output?

Lot of output.

There is probably a hacky way to do that with the buildCommand, but an integrated and portable solution would be nice ...

**Comment by webpro** [comment]
I've just released a new release ([3.1.0-beta.0](https://github.com/webpro/release-it/releases/tag/3.1.0-beta.0)) that, in interactive mode, first prints the changelog, and a confirmation question with the bumped version. You can install with:

```
npm install -g release-it@beta
```

It was helpful for myself already. Any chance you could give it a shot? Would be great to get some feedback here.

**Comment by webpro** [comment]
This is now in the [latest release](https://github.com/webpro/release-it/releases/tag/3.1.0).

**Comment by MichaelMure** [comment]
Hey,

I didn't use it yet, but thank you for your work :-)
