### ISSUE TITLE
Unexpected token "import" when using release-it not from CLI

### ISSUE THREAD

**Issue by marcuspoehls** [webpro/release-it#157]
Hey Lars,

I’m using release-it as part of a personal CLI to deploy a project. The deploy steps include test runs and actual remote command exeution. I use release-it in non-interactive mode to bump the version, commit git changes, tag git release and push the changes.

In my code, I use `release-it` like this:

```js
const ReleaseIt = require("release-it").default

ReleaseIt({
  "non-interactive": true,
  npm: {
    publish: false
  }
}).then(…)
```

The following error stack appears when running the code:

```
/Users/marcuspoehls/Dev/FutureStudio/homepage/node_modules/release-it/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { version, help } from './cli';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
```

I’m using
- Node.js `8.9.0`
- NPM `5.5.1`

Do you have an idea what goes wrong?

**Comment by webpro** [comment]
Yes, I see the issue here. release-it uses Babel to transpile the code into valid JS for the version of Node that you're currently running. You're seeing an error for the first piece of code that Node v8 does not support (yet).

Although I think the _only_ feature that is missing in Node v8 is the `import/export` syntax (ESM), release-it still needs a transpilation step for `async/await` to support Node v6.

Looks like this leaves you with two options:

1. Introduce Babel in your own project to transpile at least release-it source code, but potentially also your own.
2. I was already planning to drop support for Node v4. In that process I'll definitely consider to move back to `require()` syntax so Node v8+ doesn't require any transpilation, and using release-it programmatically would "just work"). An added benefit is improved boot performance.

The related bits in release-it (in case you'd consider the first option):

* `babel-register()` in `bin/release-it.js`
* `.babelrc`
* `babel-*` dependencies in `package.json`

**Comment by marcuspoehls** [comment]
Yeah, I guessed it’s an issue with the transpile process that I don’t do in my project. And you’re right, at this point Node.js v8 doesn’t support hte `import/export` syntax.

I want to avoid babel and will go with your suggested second option 😃This doesn’t mean you should work on it now, take your time. I went back to use `release-it` v2 which does the job.

Thank you for your support! Really appreciate it 🤝

**Comment by webpro** [comment]
Thanks! And yeah, Node v8 supports so much syntax already.

Planned some work on release-it over the weekend, so this might be in real soon.

**Comment by marcuspoehls** [comment]
😄  cool

**Comment by webpro** [comment]
The latest beta ([5.0.0-beta.0](https://github.com/webpro/release-it/releases/tag/5.0.0-beta.0)) now only uses syntax that's natively available in Node v8.

Btw, it does require e.g. Babel to transpile async/await (and maybe more) for Node v6. Support for Node v4 has been dropped.

**Comment by marcuspoehls** [comment]
Works like a charm 😗  Thank you!
