### ISSUE TITLE
Consider changing default value of requireCleanWorkingDir

### ISSUE THREAD

**Issue by owcd** [webpro/release-it#173]
I was surprised to see temporary, not excluded, files in the repository after releasing. I do understand that clean working directory is desirable, but may not be the case always. Instead of automatically adding these files and directories to the repository I would rather expect to see an error.

My proposal is to change the default value of requireCleanWorkingDir from false to true.

**Comment by webpro** [comment]
This has been the default since the beginnings. I simply found it useful at the time (as I tend to have a clean state and all excludes in `.gitignore`), but also agree it's probably the wrong default for newcomers. Once one wants to have additional changes to a release commit, this default setting can be overridden.

Having that said, the only thing before checking the clean working dir, is execution of `src.beforeStartCommand`. So probably the repo isn't in a clean state before release-it is started. Shouldn't those files also be git-ignored?

I'll leave this ticket open and change this default in the next major release. Until then, `requireCleanWorkingDir` can be overridden to `true`.

**Comment by owcd** [comment]
In version 2 of this tool I didn't notice this behavior. I have changed the configuration of my repos, but think a change of the default in next major release makes sense.

**Comment by webpro** [comment]
Nice to meet long-time users here :-)

Seems the option was introduced in [v2.1.0](https://github.com/webpro/release-it/releases/tag/2.1.0), with `false` being the default (for backwards compatibility).

**Comment by webpro** [comment]
I've just released this feature in [6.0.0-alpha.0](https://github.com/webpro/release-it/releases/tag/6.0.0-alpha.0). Would be great if you could try this on your workload.

(It also features a new `requireUpstream` to allow releasing from a new local branch.)

**Comment by webpro** [comment]
Released in [6.0.0-rc.0](https://github.com/webpro/release-it/releases/tag/6.0.0-rc.0).
