### ISSUE TITLE
bad version increment for patch release

### ISSUE THREAD

**Issue by MichaelMure** [webpro/release-it#231]
For my repo here: https://github.com/MichaelMure/Arbore/

If I ask release-it to do a patch release, it suggest the version `v0.2.1-alpha` even if the current version in both package.json is `"version": "0.2.1",` and the last git tag is `v0.2.1-alpha`.

> ? Ready to release v0.2.1-alpha? (Y/n) 

For a minor version, the suggested next version is `v0.3.0-alpha` which is correct but the changelog list all the commits since the beginning of the repository.

Could you have a look ?

Thank you

**Comment by webpro** [comment]
The `src.tagName` is used as a template to find (and set) the latest tag. That should contain `%s`, which represents the version and might include a prerelease id such as `alpha`.

So, you should remove `-alpha` from your `tagName` (and `commitMessage`).

**Comment by MichaelMure** [comment]
So, I did what you suggested (https://github.com/MichaelMure/Arbore/commit/c4f6f66c049813e1ba7fbc43c9afbcd3b4eb164b), here is the result:
- 👍 the correct version number is suggested
- 👎 the `preReleaseId` doesn't seems to work. The suggested version is `0.2.2`, not `0.2.2-alpha`.
- 👎 the root `package.json` is properly updated and ready to commit in git, but doesn't show when using `Show updated files?` (see  below). Maybe you need something like `git diff --cached` ?
- 👎 only the root `package.json` is updated. The secondary `app/package.json` is not updated. That was working properly before.

> Release source repo
? Show updated files? Yes
undefined
? Commit (Release 0.2.2)? (Y/n) 

Thank you

**Comment by webpro** [comment]
Let's consider the incrementing the version only in this ticket. I'll look into the updated/bumped files after this.

Please see https://github.com/webpro/release-it#-manage-pre-releases. A few comments:

* The `preReleaseId` is the identifier to use *if* a pre-release is done. A pre-release is done by incrementing with "prepatch", etc.
* I recommend to use e.g. `--preRelease=alpha` from the command-line (which is a shortcut as the docs describe). This also abstracts away the fact that `semver` (the dependency release-it uses) requires to use an increment of "prerelease" for pre-release continuations (e.g. to go from `0.2.1-alpha.0` to `0.2.1-alpha.1`).
* Incrementing from `0.2.1-alpha` to `0.2.2-alpha` would not follow semver.
* The `0.2.1-alpha` can still be incremented to `0.2.1-alpha.0` with `--preRelease=alpha`.

Assuming the latest tag was `0.2.1`, and we want to pre-release for the next patch release (i.e. working towards `0.2.2`):

```
release-it preRelease=alpha
```

Now `0.2.2-alpha.0` will be tagged (since "patch" is the default increment). Another pre-release with the same command will result in `0.2.2-alpha.1`. Now, to release `0.2.2`:

```
release-it
```

Hopefully this makes some kind of sense :-)

(I'll add some extra unit tests to prevent regressions.)

**Comment by webpro** [comment]
Not able to reproduce issues with multiple manifest files (e.g. `app/package.json`). Can you confirm, or make a reproducible test case? Maybe the version was "out-of-sync" and didn't need an update?

**Comment by MichaelMure** [comment]
Ha, I was indeed using semver wrong.

For the double package.json, you can test with my repo: https://github.com/MichaelMure/Arbore. But now that I think of it, that might be due to the same semver misanderstanding.
