### ISSUE TITLE
Release-it only tags source repo

### ISSUE THREAD

**Issue by Necroskillz** [webpro/release-it#38]
Hi,

seems that change in commit 6179c5d10b8e7faf338baea69bf838772a67069e made it so that the dist repo is not tagged. I understand from the commit message that this is for the case that dist repo is the same as source repo (dunno when does that make sense), however that is not our case - the source and dist repo are different and both should be tagged.

**Comment by webpro** [comment]
The dist repo is the same if the release goes to another branch (example: [gh-pages branch](https://medium.com/@webprolific/using-github-pages-the-easy-way-bb7acc46f45b)).

But I tried to be smart here, and not ask the tag question in that particular case. I'm going to see if I can detect whether src/dist repo have the same origin (probably not a good idea). Otherwise, probably, ending up with asking the tag question twice, always.

**Comment by Necroskillz** [comment]
You can always add another config property which defines whether to tag the dist repo
