### ISSUE TITLE
Variables can't be used in asset globs

### ISSUE THREAD

**Issue by beaugunderson** [webpro/release-it#401]
This is what I'm attempting to do:

```json
{
  "buildCommand": "yarn dist",
  "github": {
    "release": true,
    "assets": [
      "dist/*${version}.exe",
      "dist/*${version}-mac.zip"
    ],
    "tokenRef": "RELEASE_IT_TOKEN"
  }
}
```

```
WARNING octokit releases#uploadAssets: assets not found (glob "dist/*${version}.exe,dist/*${version}-mac.zip" relative to /Users/beau/p/tracking-tool)
```

**Comment by webpro** [comment]
Hi, @beaugunderson. That is expected behavior. Only in [command hooks](https://github.com/webpro/release-it#command-hooks) (and soon commits messages and tags) variables are substituted.

Not sure whether adding this feature as you're trying to use it is a good idea as it may get muddy or conflict with glob syntax/characters.

**Comment by beaugunderson** [comment]
@webpro makes sense to me! i worked around by adding `rm -rf dist/` in my package.json `script.dist` entry so that prior versions will never exist, and then just used `dist/*.exe` and `dist/*-mac.zip` for the globs :+1:
